const posts = [
  {
    id: 1,
    title: "Début officiel de la collaboration entre Relais Thalasso group et beScored",
    href: "#",
    description: "Avec 4 sites d'exception, les Relais Thalasso sont des pionniers dans la thalassothérapie. Ils ont décidé de travailler avec nous et d'utiliser sur chaque site notre solution digitale MASAK afin de quantifier les effets des cures Equilibre Thalavie. Merci à Jean-pascal et Anne Phelippeau, ainsi qu'a son Directeur général Jean-luc Pleuvry.",
    imageUrl: "/images/news/10.jpg",
    date: "Janvier 2025",
    datetime: "Janvier 2025",
    category: { title: "Collaboration", href: "#" },
    author: {
      name: "Christophe Hausswirth",
      role: "beScored",
      href: "#",
      imageUrl: "/images/chris.jpg",
    },
  },
  {
    id: 2,
    title: "Conférence de C. Hausswirth au salon des Thermalies, Paris",
    href: "#",
    description: "Ce mois de janvier a permis de proposer un stand montrant notre solution MASAK pour la première fois : clients et professionnels des soins (thermalisme, thalassothérapie, SPA, etc.) ont pu être évalués. En marge du salon, C. Hausswirth a pu donner 1h30 de conférence autour du stress, du vieillissement et du sommeil.",
    imageUrl: "/images/news/11.jpg",
    date: "Janvier 2025",
    datetime: "Janvier 2025",
    category: { title: "Conférence", href: "#" },
    author: {
      name: "Christophe Hausswirth",
      role: "beScored",
      href: "#",
      imageUrl: "/images/chris.jpg",
    },
  },
  {
    id: 3,
    title: "Installation du MASAK dans la station thermale d'Ax-Les-Thermes",
    href: "#",
    description: "C'est la station thermale d'Ax-les-Thermes (en Ariège) qui aura été la première station thermale à nous faire confiance. Nous avons installé et formé le personnel sur la méthodologie de notre solution digitale MASAK. Un nouveau moyen d'évaluer avec objectivité la pertinence des cures thermales et les soins du SPA thermal. Merci à sa Directrice générale, Anne Chevalier, pour sa confiance.",
    imageUrl: "/images/news/12.jpg",
    date: "Février 2025",
    datetime: "Février 2025",
    category: { title: "Installation", href: "#" },
    author: {
      name: "Christophe Hausswirth",
      role: "beScored",
      href: "#",
      imageUrl: "/images/chris.jpg",
    },
  },
  {
    id: 4,
    title: "Collaboration avec La Demeure Club (Saint-Cloud)",
    href: "#",
    description: "Nous collaborons depuis un an déjà avec ce centre de bien-être avancé dans lequel nous venons d'installer notre MASAK. Il permet, pour ce centre, d'être un acteur de la prévention notamment dans le cas de surmenage professionnel. Merci à Céline Foster pour sa confiance et la pertinence de son approche.",
    imageUrl: "/images/news/13.jpg",
    date: "Mars 2025",
    datetime: "Mars 2025",
    category: { title: "Collaboration", href: "#" },
    author: {
      name: "Christophe Hausswirth",
      role: "beScored",
      href: "#",
      imageUrl: "/images/chris.jpg",
    },
  },
  {
    id: 5,
    title: "Collaboration avec la station thermale Avène",
    href: "#",
    description: "Ce mois d'avril a été riche dans les installations de notre solution digitale MASAK. Le centre thermal vient de s'équiper de notre système d'évaluation objective du bien-être mental et physique. Ce sera pour eux l'occasion de mettre en avant l'efficacité de leurs cures thermales sur mesure, notamment autour des maladies de peau.",
    imageUrl: "/images/news/14.jpg",
    date: "Avril 2025",
    datetime: "Avril 2025",
    category: { title: "Collaboration", href: "#" },
    author: {
      name: "Christophe Hausswirth",
      role: "beScored",
      href: "#",
      imageUrl: "/images/chris.jpg",
    },
  },
  {
    id: 6,
    title: "Participation au Medi-Wellness Congress (MWC), Genève",
    href: "#",
    description: "Alexandre Coste et Geoffrey Millour ont pu proposer de tester notre solution MASAK au monde du SPA au niveau européen notamment. Ce fut l'occasion d'échanger avec de grands groupes comme Valmont ou La Prairie. Merci aux organisateurs de ce bel évènement.",
    imageUrl: "/images/news/15.jpg",
    date: "Avril 2025",
    datetime: "Avril 2025",
    category: { title: "Événement", href: "#" },
    author: {
      name: "Christophe Hausswirth",
      role: "beScored",
      href: "#",
      imageUrl: "/images/chris.jpg",
    },
  },
  {
    id: 7,
    title: "Kick-off de l'étude sur l'impact des massages robotisés sur la récupération sportive du golfeur",
    href: "#",
    description: "Ce début Mai a été marqué par le lancement de notre nouvelle étude réalisée au Golf de la Grande bastide (Châteauneuf-de-grasse). Nous allons étudier avec la société CAPSIX les effets des massages journaliers sur la récupération et la performance des golfeurs et golfeuses séniors (65 ans). Merci à Alexis Davet, directeur du golf, pour cet accueil et cette collaboration.",
    imageUrl: "/images/news/16.jpg",
    date: "Mai 2025",
    datetime: "Mai 2025",
    category: { title: "Étude", href: "#" },
    author: {
      name: "Christophe Hausswirth",
      role: "beScored",
      href: "#",
      imageUrl: "/images/chris.jpg",
    },
  },
  {
    id: 8,
    title: "Visite et réunion au Campus PSG",
    href: "#",
    description: "C. Hausswirth a été invité par le Chef Médical, Dr. Hakim CHALABI, à une réunion d'échanges sur la récupération sportive. Les préparateurs physiques (Maxime Coulerot en pilote), les kinésithérapeutes, les médecins, les nutritionnistes et le Staff sont au cœur des échanges pour ce projet transversal.",
    imageUrl: "/images/news/17.jpg",
    date: "Mai 2025",
    datetime: "Mai 2025",
    category: { title: "Réunion", href: "#" },
    author: {
      name: "Christophe Hausswirth",
      role: "beScored",
      href: "#",
      imageUrl: "/images/chris.jpg",
    },
  },
];

export default posts;
